### ISSUE TITLE
Wildcard nodes will not work if the plugin does not know how to handle them

### ISSUE THREAD

**Issue by l1ttleO** [ElgarL/GroupManager#56]
**Description**
See title

**Steps to reproduce**
1. Get a plugin that does not know how to handle wildcard nodes ([Here's one I made](https://github.com/l1ttle-org/test-plugin/releases/))
2. Grant a wildcard node (* or plugin.*)
3. Try to use a command for that plugin (any permission check for vanilla commands will fail too!)
4. See that the permission check failed, even tho you have the wildcard node

**Expected behavior**
The permission check will succeed because of the wildcard node

**Screenshots**
![image](https://user-images.githubusercontent.com/61277953/98437318-048e8680-2103-11eb-9a97-431020378673.png)

**Please complete the following information:**
 - OS: Linux 5.4.0-52-generic
 - Paper/Spigot version: Tuinity 1.16.4
 - Plugin version: v2.9-SNAPSHOT

**Additional context**
Add any other context about the problem here, **including any error logs**.

**Comment by ElgarL** [comment]
This isn't a bug with GM as GM only knows about perms which are defined correctly by the plugin (plugin.yml)
If you use the GM API it will return a result of true for ANY wildcard perm as per your screen shot.
However when you test Player.hasPerm it will test false due to Bukkit not knowing about your undefined wildcard.

In your example you only have testplugin.testperm defined. Internally GM will handle wildcards of that, but it can only push defined child perms to Bukkit.

**Comment by l1ttleO** [comment]
LuckPerms does not have this. That's the main reason I reported this. Maybe it's not a bug, but a feature request perhaps?

**Comment by ElgarL** [comment]
Its impossible to do without hackery. LuckPerms handles it by reflection and replacing the permission check on the player.
