### ISSUE TITLE
[Request] Sync across Bungee servers

### ISSUE THREAD

**Issue by pythros** [ElgarL/GroupManager#7]
The title is basically it. Would it be possible to make it so that if we modified the user that it'll sync across designated servers within that Bungee instance? For example, if I have a user added to Member in server H1 that it will become a Member in H2? I'm trying to get it so we don't have to have the user do this more than once.

**Comment by ElgarL** [comment]
This has been mentioned before but I've not really taken much interest in it as I've never worked with Bungie.
I'll take a look when I get time.

**Comment by ElgarL** [comment]
I have investigated the possibility of this being achieved via plug-in messaging, however its not possible due to messages only being able to be sent to a server if it has players logged in.

**Comment by pythros** [comment]
Thank you for looking into it further.

Are you saying:

Server A: User H gets group Z. In order for Server B to set user H to group Z they would have to be on Server B at the same time?
What about a companion plugin that runs on the BungeeCord instance? Or, the option of SQL to store the user's groups?

We already tried to symlink the users.yml and many things did not like that.

**Comment by ElgarL** [comment]
For a server to receive a plug-in channel message it needs at least one player on that server. It doesn't matter who it is, but it requires one player to be on each server that wants to listen.
A central SQL backend would work however, it would also require a major rewrite to how GM handles its data.
The issue you likely found with using symlinks is that GM only saves every 10 minutes, and although it does check if the data files have been altered since it last checked it will not automatically load changes unless instructed to do so with a /manload

**Comment by pythros** [comment]
I see. The problem with the symlink wasn't the data didn't sync over, it
was there were several errors from different plugins when a player logged
into the server.

**Comment by ElgarL** [comment]
Odd, other plug-ins should not care about a symlink on a GM data folder.

**Comment by ElgarL** [comment]
This is now available in the Experimental build.
Set database to MySQL or any database all servers can access. Set save duration to 1 minute.

**Comment by pythros** [comment]
Awesome. Thank fir doing this!
