### ISSUE TITLE
[Tab complete i fu**ed] 

### ISSUE THREAD

**Issue by MrmaximoExcssum** [ElgarL/GroupManager#9]
Paper 1.16.1 
non op players can see all commands + more wierd tabcomplete bugs

**Comment by ElgarL** [comment]
The ability to see commands is a feature of Spigot via command permissions. As all commands now register individually they are now controlled by that API.
I'd be interested in what other tab-complete issues you have.

**Comment by ElgarL** [comment]
I've updated the 2.5-SNAPSHOT so it correctly registers all GM perms allowing Spigot to restrict the commands accessed.
This will not remove a command from those offered in tab-complete as thats up to Spigot, but it will prevent any GM commands tab-completing in any way if the player does not have permissions to use the command.

If you have any further issues please open a new ticket, or respond to this one if the issue is not fixed.
